language: ruby
sudo: false
before_install:
  - gem install bundler
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
matrix:
  allow_failures:
    - rvm: 2.1.5
    - rvm: 2.2.0
